[build]
  publish = "."

[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/en/*.html"
  to = "/pages/en/:slug"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/es/*.html"
  to = "/pages/es/:slug"
  status = 301
  force = true
