[build]
  publish = "."

[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/EN/*.html"
  to = "/pages/EN/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/pages/ES/*.html"
  to = "/pages/ES/:splat"
  status = 200
  force = true
