[build]
  publish = "."

[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/*"
  to = "/pages/:splat.html"
  status = 301
  force = true
  # Apenas redireciona se a URL não terminar com `.html`
  conditions = { "url" = "!/.html$" }

  [[redirects]]
  from = "/pages/en/*"
  to = "/pages/en/:splat.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/es/*"
  to = "/pages/es/:splat.html"
  status = 301
  force = true
