[build]
  publish = "."

[[redirects]]
  from = "/termos"
  to = "/termos.html"
  status = 200
  force = true

[[redirects]]
  from = "/sobre"
  to = "/sobre.html"
  status = 200
  force = true

  [[redirects]]
  from = "/proposito"
  to = "/proposito.html"
  status = 200
  force = true

  [[redirects]]
  from = "/politica"
  to = "/politica.html"
  status = 200
  force = true

  [[redirects]]
  from = "/pay"
  to = "/pay.html"
  status = 200
  force = true

[[redirects]]
  from = "/contato"
  to = "/contato.html"
  status = 200
  force = true

# Rotas inglês
[[redirects]]
  from = "/en/termos"
  to = "/en/termos.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/proposito"
  to = "/en/proposito.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/politica"
  to = "/en/politica.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/pay"
  to = "/en/pay.html"
  status = 200
  force = true

[[redirects]]
  from = "/en"
  to = "/en/en.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/contact"
  to = "/en/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/about"
  to = "/en/about.html"
  status = 200
  force = true

# Rotas espanhol
[[redirects]]
  from = "/es/termos"
  to = "/es/termos.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/sobre"
  to = "/es/sobre.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/proposito"
  to = "/es/proposito.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/politica"
  to = "/es/politica.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/pay"
  to = "/es/pay.html"
  status = 200
  force = true

[[redirects]]
  from = "/es"
  to = "/es/es.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/contato"
  to = "/es/contato.html"
  status = 200
  force = true