[build]
  publish = "."

[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/:splat"
  to = "/pages/:splat.html"
  status = 301
  force = true

  [[redirects]]
  from = "/pages/en/*"
  to = "/pages/en/:splat.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/es/*"
  to = "/pages/es/:splat.html"
  status = 301
  force = true
